### ISSUE TITLE
DEPLOY - libsodium fails to build

### ISSUE THREAD

**Issue by drobati** [drobati/alia-bot#1]
```
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/var/www/alia-bot/node_modules/sodium/deps/libsodium':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** [Makefile:63: libsodium] Error 77
/var/www/alia-bot/node_modules/sodium/install.js:293
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/var/www/alia-bot/node_modules/sodium/install.js:293:19)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@3.0.2 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@3.0.2 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-19T03_11_35_701Z-debug.log
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: ../index.js
```

Libsodium finds gcc, but fails with `checking whether the C compiler works... no`. Further details stored on machine.

**Comment by drobati** [comment]
Removed the dependency. I believe the newer discordjs didn't require it.
